controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    
    lift_position_controller:
      type: position_controllers/JointGroupPositionController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

lift_position_controller:
  ros__parameters:
    joints:
      - lift_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity